spring.application.name=lms
spring.datasource.url=jdbc:postgresql://localhost:5432/lms_db
spring.datasource.username=postgres
spring.datasource.password=1270

spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true